### ISSUE TITLE
Travis build failing for unknown reason

### ISSUE THREAD

**Issue by sanketsarang** [blobcity/db#65]
The automated build on Travis fails without clarity on reason of failure. The project compiles successfully when tried on developers computer.

**Comment by jwojciec** [comment]
Hello, I'm investigating this.

So far found in travis logs:
`[ERROR] COMPILATION ERROR : 
[INFO] -------------------------------------------------------------
[ERROR] /home/travis/build/blobcity/db/engine/src/main/java/com/blobcity/db/apache/tikka/TikaPdfInterpreter.java:[55,22] cannot access org.apache.tika.config.Initializable
class file for org.apache.tika.config.Initializable not found`

**Comment by sanketsarang** [comment]
@jwojciec Awesome. Please send a pull request when you have a solution. The same build works with `mvn clean package` on every computer we have tried. The `org.apache.tika.config.Initializable` class is successfully found when running the build. Travis throws the error though.

**Comment by jwojciec** [comment]
@sanketsarang fixed under https://github.com/blobcity/db/pull/67
It was a matter of travis.yml config and for some reason, Travis has problems with version range (like [1.20,) for tika-core). Is tika-core 1.20 fine or should I update it to the lates?

**Comment by sanketsarang** [comment]
@jwojciec Got it. Let's update tike-core to the latest stable release.

**Comment by jwojciec** [comment]
Done, tika-core bumped to latest. Build is still passing.

**Comment by sanketsarang** [comment]
Awesome. Thanks @jwojciec
